### PR TITLE
Create de.po

### PR DESCRIPTION
**Pull request by YugiFanGX**

### CODE REVIEW

**Comment by YugiFanGX** [comment]
@mardy  Can you check why the built failed?

**Comment by Flohack74** [comment]
Probably your branch name should be xenial_-_<somename>

**Comment by YugiFanGX** [comment]
@Flohack74  But didn't you write that everything should be merged to master? https://github.com/ubports/account-plugins/pull/9

**Comment by Flohack74** [comment]
Our CI does only build your branch correctly when you specify what base system you use. So your branch needs to have a different name, not ours ^^

**Comment by YugiFanGX** [comment]
I don't understand what I should do. My branch is patch-2?
What should I do on the github page?

**Pull request closed without merging**
