### PR TITLE
special chars fix

### PR DESCRIPTION
**Pull request by YugiFanGX**
special chars

### CODE REVIEW

**Comment by YugiFanGX** [comment]
@Flohack74 Are you able to merge this to master?

**Comment by Flohack74** [comment]
What is the difference to #30 ?

**Comment by YugiFanGX** [comment]
One was meant for owncloud, the other one is for nextcloud

**Comment by Flohack74** [comment]
Please merge the changes into one PR. You are changing one line in each, thats a waste of resources of Github ;)

**Comment by YugiFanGX** [comment]
PR?

**Comment by Flohack74** [comment]
Pull request. You can add both changes into #30 please.

**Pull request closed without merging**
