### PR TITLE
Use the external browser for Google authentication

### LINKED ISSUE #40: Google: Unable to sign in Again
Guess this user agent string is also blocked.

### PR DESCRIPTION
**Pull request by mardy**
This MR depends on https://github.com/ubports/ubuntu-system-settings-online-accounts/pull/16

This fixes: https://github.com/ubports/account-plugins/issues/40, at the cost of making the authentication flow less user-friendly (but this is what Google explicitly asks us to do).

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I've noticed that there is no button to close the new Google account interface.

image

If the user navigates back to system-settings without completing the login, they are unable to leave the Google login due to this.

**Review by UniversalSuperBox — DISMISSED** [review]
Blocking review due to ^

**Comment by mardy** [comment]
> Blocking review due to ^

I added a Cancel button now, but I'm unable to test it. Will you please give it a try?

**Comment by amartinz** [comment]
[Dependency](https://github.com/ubports/ubuntu-system-settings-online-accounts/pull/16) has landed.

**Comment by amartinz** [comment]
Tested with logging in a family link enabled account (so had to log in the account as well as logging in a second time with the parent account).

Cancel button is there as well and is functional :smile:

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
