### PR TITLE
Update UserAgent

### PR DESCRIPTION
**Pull request by rubencarneiro**
Make google accounts sync again.

### CODE REVIEW

**Comment by mardy** [comment]
I'm unable to test it, unfortunately. I hope that someone else from the community can give this a try?

**Review by GI9VANNI — APPROVED** [review]
It worked on my Nexus 5!

**Comment by rubencarneiro** [comment]
> It worked on my Nexus 5!

Nice.

**Comment by wiredsis** [comment]
Didn't work for me on my Mi A3.

**Comment by rubencarneiro** [comment]
> Didn't work for me on my Mi A3.

retry to install and reboot

**Comment by Verevka** [comment]
Work perfect! Xiaomi mi6 halium 9.0 .

**Comment by UniversalSuperBox** [comment]
It seems like the user-agent and the block are basically random for every user. Trying to change the user agent every time someone files this issue will only lead to an insane game of whack-a-mole where no one wins, unfortunately...

For more information about the issue, please see the discussion in https://github.com/ubports/account-plugins/issues/40#issuecomment-613547348

**Pull request closed without merging**
