### PR TITLE
Allow special character for user and pass

### PR DESCRIPTION
**Pull request by YugiFanGX**

### CODE REVIEW

**Comment by YugiFanGX** [comment]
@Flohack74  Please merge this to master

**Comment by YugiFanGX** [comment]
@mardy Or can you add these pull requests?

**Comment by Flohack74** [comment]
I need @mardy to review this...

**Comment by YugiFanGX** [comment]
@mardy more than a week is over. can you merge it now?

**Comment by mardy** [comment]
Hi @YugiFanGX , I was waiting for you to confirm that you actually tested the changes and that they are working for you: https://github.com/ubports/ubuntu-touch/issues/893#issuecomment-429657977
Please let me know if you have tested this, and I'll merge it.

**Comment by YugiFanGX** [comment]
It will work.

**Comment by YugiFanGX** [comment]
@mardy  I am not sure if the syncing with the calendar works correctly. where can i find the code?

**Comment by mardy** [comment]
@YugiFanGX: it's [here](https://github.com/ubports/sync-monitor), just make sure you checkout the `xenial` branch.

**Pull request merged**
